### ISSUE TITLE
Text selection is unreadable

### ISSUE THREAD

**Issue by pansy27** [rose-pine/helix#1]
Hello.

I was trying out rose pine themes for helix text editor when i found out that "Text highlight **background color**" for both of these themes is the same as normal background color of the theme which makes it impossible to look at the highlight text as it appears as a solid color block. Here are some screenshots of the problem i am facing: 

### Rose pine dawn :
![21_56_25](https://user-images.githubusercontent.com/88635622/151400998-d541b837-6197-4d11-9175-a2e70e29f911.png)

### Rose pine :
![21_56_41](https://user-images.githubusercontent.com/88635622/151401299-1979b481-62f9-4eb2-b861-e24cb803849f.png)

### Base 16 default dark for comparison:
![21_56_59](https://user-images.githubusercontent.com/88635622/151401429-802a82d8-09f4-43cd-b5dd-6f6d4fecaed6.png)

### Base 16 default light:
![22_ 1_03](https://user-images.githubusercontent.com/88635622/151401744-8a88e5a3-52ab-4347-8895-922aeead814b.png)

In all of the screenshots i am selecting the same text, from line 71 to line 81.

I tried all of these themes on a clean install of helix. I have made no changes whatsoever to the highlight part of the text editor.

**Comment by mvllow** [comment]
We noticed that too 😔 Unfortunately we didn't make these themes but we do love helix so will look into getting that updated!

**Comment by pansy27** [comment]
I see. Thank you for looking into this.

**Comment by mvllow** [comment]
Looks like this was fixed in https://github.com/helix-editor/helix/pull/1716 🎉
