### ISSUE TITLE
Inline-hints

### ISSUE THREAD

**Issue by LeoniePhiline** [rose-pine/helix#2]
Helix now supports inline hints. Rose-pine does not color them appropriately (i.e. toned down), but shows them white, like normal text. 

Would you mind choosing a color for `"ui.virtual.inlay-hint"`?

Previously (without inline hints):
![image](https://user-images.githubusercontent.com/22329650/225759791-f7259876-e4d1-485f-9f4a-2907c0d20a12.png)

Now (with inline hints, but they are colored white and indistinguishable from non-virtual text):
![image](https://user-images.githubusercontent.com/22329650/225759826-68b7e36e-1f4d-438b-b454-d3b4b499c574.png)

Rose pine moon is used for the above screenshots.

Implementation hints can be taken from recently closed "inlay hints" PRs, as all themes are getting the new setting one after the other: https://github.com/helix-editor/helix/pulls?q=is%3Apr+inlay+hint+is%3Aclosed

**Comment by mvllow** [comment]
Thanks for pointing this out! Would it make sense to have hints similar to comments?

**Comment by LeoniePhiline** [comment]
Yes, I think so.
