### ISSUE TITLE
Helix vs Neovim vs VSCode

### ISSUE THREAD

**Issue by nshern** [rose-pine/helix#6]
Helix, Neovim and VSCode all look different using Rosé Pine.

As a Helix and Rosé Pine user I would glady help tweaking it, but would need to know which one to look at for guidance? i.e. Which implementation is considered "canon"?

**Comment by mvllow** [comment]
The Neovim version is our most frequently updated. I'm curious if Helix has added more highlight groups recently (ish). Would love see any before/after screenshots and if you need help with anything just ask (:

**Comment by mvllow** [comment]
Closed by #7 :)

**Comment by nshern** [comment]
@mvllow, do you have plans to make a PR to merge the changes to Helix? If you want, I would glady do it myself.

**Comment by mvllow** [comment]
If you have time, please do, thank you!

Edit: Let me know if you'd like to be a maintainer of this repo—if not no worries :) I don't personally use Helix (yet) so it's a lower priority for me.

**Comment by nshern** [comment]
> If you have time, please do, thank you!
> 
> Edit: Let me know if you'd like to be a maintainer of this repo—if not no worries :) I don't personally use Helix (yet) so it's a lower priority for me.

Sure thing - I would love to be a maintainer.
