### ISSUE TITLE
Unclear syntax highlighting for Markdown wikilinks

### ISSUE THREAD

**Issue by th7mo** [rose-pine/helix#9]
Hi! I love the Rose Pine Moon theme for Helix, but I have a small improvement that could be made imo.
When writing Markdown, the wikilink syntax can be improved.

Now it is hard to detect wikilinks in large leaps of text:
![image](https://github.com/rose-pine/helix/assets/73542945/bc862604-64d1-4090-8dab-dc79f37ca03e)

I think the theme can improve if the color for link text (the text inside `[` and `]` was changed to any other color.
The suggested change is also the default on almost every other Helix theme.

This can be done by changing `"markup.link.text" = "text"` to another color.
How about the `rose` (`#ebbcba`)?
It would look something like this:
![image](https://github.com/rose-pine/helix/assets/73542945/1fde693a-d97b-4309-8825-d0d1b3538ced)

I this is a beneficial change let me know, I can make a PR for it.

**Comment by mvllow** [comment]
My first thought would be to try underlining the text, similar to the link itself. If that's confusing (or if a colour is simply preferred) then perhaps gold as it usually represents strings? I would have to review what other colours, if any, are common in markdown files in both Helix and Neovim & if rose isn't heavily used than that could work as well :)

_Note to self: Whatever is decided here should also be ported to our Neovim theme_

**Comment by th7mo** [comment]
@mvllow I think the underline should be preserved for clickable elements, like the https link provided in the screenshot example. This is a common convention for modern terminal emulators.

I also think that other colors like gold will work just fine, as long as it significantly distincts itself from plain text. The distinction is the primary goal of this issue.

Another color to consider is a blue-ish color in the rose-pine pallete since every browser renders (unvisited) links blue, so this is very intuitive and user friendly to make link text blue.

I suggested rose in the first place since it is the primary accent color, which is always a safe option.

**Comment by mvllow** [comment]
Fair point about the underline. A PR would be appreciated, changing it to one of foam, gold, or rose—your choice :)
